url: "/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Final Cooking Fantasy" # the name of your site, e.g. ACME Corp.

permalink: /:collection/:name

collections_dir: recipes

collections:
  mains:
    output: true

  sides:
    output: true

  sauces:
    output: true

  treats:
    output: true

defaults:
  -
    scope:
      path: ""
      type: mains
    values:
      layout: "recipe"

  -
    scope:
      path: ""
      type: sides
    values:
      layout: "recipe"

  -
    scope:
      path: ""
      type: sauces
    values:
      layout: "recipe"

  -
    scope:
      path: ""
      type: treats
    values:
      layout: "recipe"
